import tour1 from "../assets/tour1.jpg";
import tour2 from "../assets/tour2.jpg";
import tour3 from "../assets/tour3.jpg";
export const budgetpackages = [
  {
    id: 1,
    title: "Sri Lanka 4-Day Budget Tour",
    subtitle: "4-Days Tours",
    duration: "4 Days",
    image: tour1,
    highlights: [
      "Sigiriya Rock Fortress",
      "Dambulla Cave Temple",
      "Polonnaruwa Ancient City",
      "Kandy Temple of the Tooth",
      "Scenic Train to Ella",
      "Yala Safari",
      "Mirissa Coconut Hill",
      "Galle Fort & Turtle Hatchery",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    title: "5-Day Budget Tour of Sri Lanka",
    subtitle: "5 Days Tours",
    duration: "5 Days",
    image: tour2,
    highlights: [
      "Temple of the Tooth",
      "Cultural Heritage Sites",
      "Traditional Cuisine",
    ],
    rating: 4.9,
    reviews: 89,
  },
  {
    id: 3,
    title: " 5-Day South & City Budget Tour – Sri Lanka",
    subtitle: "5 Days Tours",
    duration: "5 Days",
    image: tour3,
    highlights: [
      "Climb Sigiriya Rock Fortress",
      "Explore Ancient Polonnaruwa & Dambulla Caves",
      "Wildlife Safari at Minneriya & Yala",
      "Temple of the Tooth Relic in Kandy",
      "Scenic train ride from Nuwara Eliya to Ella",
      "Nine Arch Bridge & Little Adam’s Peak",
      "Whale Watching in Mirissa",
      "Galle Fort & Turtle Hatchery",
      "Bentota Beach & Madu River Safari",
    ],
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 4,
    title: " 6-Day Sri Lanka Budget Tour",
    subtitle: "6 Days Tours",
    duration: "6 Days",
    image: tour3,
    highlights: [
      "Climb Sigiriya Rock Fortress",
      "Explore Ancient Polonnaruwa & Dambulla Caves",
      "Wildlife Safari at Minneriya & Yala",
      "Temple of the Tooth Relic in Kandy",
      "Scenic train ride from Nuwara Eliya to Ella",
      "Nine Arch Bridge & Little Adam’s Peak",
      "Whale Watching in Mirissa",
      "Galle Fort & Turtle Hatchery",
      "Bentota Beach & Madu River Safari",
    ],
    rating: 4.9,
    reviews: 156,
  },
];
