import tour1 from "../assets/tour1.jpg";
import tour2 from "../assets/tour2.jpg";
import tour3 from "../assets/tour3.jpg";

export const srtpackages = [
  {
    id: 1,
    title: "8-Days Sri Lanka Cultural & Nature Sightseeing Tour",
    subtitle: "8-Days Tours",
    duration: "8 Days",
    image: tour1,
    highlights: [
      "Sigiriya Rock Fortress",
      "Dambulla Cave Temple",
      "Polonnaruwa Ancient City",
      "Kandy Temple of the Tooth",
      "Scenic Train to Ella",
      "Yala Safari",
      "Mirissa Coconut Hill",
      "Galle Fort & Turtle Hatchery",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    title: "Sri Lanka 3-Days South Coast Discovery Tour",
    subtitle: "3 Days Tours",
    duration: "3 Days",
    image: tour2,
    highlights: [
      "Temple of the Tooth",
      "Cultural Heritage Sites",
      "Traditional Cuisine",
    ],
    rating: 4.9,
    reviews: 89,
  },
  {
    id: 3,
    title: "10-Day Sri Lanka Heritage, Nature & Culture Tour",
    subtitle: "10 Days Tours",
    duration: "10 Days",
    image: tour3,
    highlights: [
      "Climb Sigiriya Rock Fortress",
      "Explore Ancient Polonnaruwa & Dambulla Caves",
      "Wildlife Safari at Minneriya & Yala",
      "Temple of the Tooth Relic in Kandy",
      "Scenic train ride from Nuwara Eliya to Ella",
      "Nine Arch Bridge & Little Adam’s Peak",
      "Whale Watching in Mirissa",
      "Galle Fort & Turtle Hatchery",
      "Bentota Beach & Madu River Safari",
    ],
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 4,
    title: "5-Day Sri Lanka Cultural Discovery Tour",
    subtitle: "5 Days Tours",
    duration: "5 Days",
    image: tour2,
    highlights: [
      "Dambulla Golden Cave Temple (UNESCO)",
      "Climb Sigiriya Rock Fortress",
      "Anuradhapura & Mihintale",
      "Ancient Polonnaruwa ruins",
      "Minneriya Elephant Safari",
      "Matale Spice Garden & Nalanda Gedige",
      "Temple of the Tooth in Kandy",
      "Gadaladeniya, Lankatilaka & Embekka Temples",
    ],
    rating: 5.0,
    reviews: 203,
  },
  {
    id: 5,
    title: "12 Days Cultural Heritage Tour of Sri Lanka",
    subtitle: "12 Days Tours",
    duration: "12 Days",
    image: tour1,
    highlights: [
      "Colombo City exploration",
      "Gangaramaya & Kelaniya Temples",
      "Galle Fort & Madu River Safari",
      "Yala National Park safari",
      "Ella sightseeing – Ravana Falls, Nine Arch Bridge & Little Adam’s Peak",
      "Scenic train journey to Nuwara Eliya",
      "Lake Gregory & Sita Amman Temple visit",
      "Ramboda Falls & Tea Plantation experience",
      "Kandy cultural city tour & Temple of the Tooth",
      "Matale Spice Garden & Muthumariamman Temple",
      "Sigiriya Rock Fortress & Dambulla Cave Temple",
      "Polonnaruwa Ancient City & Minneriya Safari",
      "Anuradhapura Sacred City & Mihintale",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 6,
    title: "14 Days Sightseeing Adventure Across Sri Lanka",
    subtitle: "14 Days  Tours",
    duration: "14 Days ",
    image: tour3,
    highlights: [
      "Relax in Negombo fishing village & Dutch heritage sites",
      "Explore sacred Anuradhapura & Mihintale",
      "Climb Sigiriya Rock Fortress (UNESCO)",
      "Discover ancient ruins of Polonnaruwa",
      "Wildlife safari at Minneriya & Yala National Park",
      "Visit Dambulla Golden Cave Temple (UNESCO)",
      "Spice Garden & Matale Muthumariamman Temple",
      "Kandy City Tour & Temple of the Tooth Relic",
      "Witness Pinnawala Elephant Orphanage",
      "Climb Adam’s Peak pilgrimage trail",
      "Scenic train ride from Nuwara Eliya to Ella",
      "Nine Arch Bridge, Little Adam’s Peak & Ravana Falls",
      "Beach bliss in Mirissa with whale watching",
      "Galle Fort, Turtle Hatchery & Madu River safari in Bentota",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 7,
    title: "12 Days Sri Lanka Sightseeing Tour",
    subtitle: "12 Days Tours",
    duration: "12 Days",
    image: tour1,
    highlights: [
      "Relax at Negombo beach town",
      "Visit Mihintale – birthplace of Buddhism in Sri Lanka",
      "Explore the sacred city of Anuradhapura (UNESCO)",
      "Discover the ruins of Polonnaruwa (UNESCO)",
      "Jeep Safari at Minneriya National Park",
      "Climb the legendary Sigiriya Rock Fortress (UNESCO)",
      "Visit Dambulla Golden Cave Temple (UNESCO)",
      "Spice Garden & Hindu Temple at Matale",
      "Kandy City Tour & Temple of the Tooth Relic",
      "Tea plantations & waterfalls in Nuwara Eliya",
      "Hike at Horton Plains & World’s End",
      "Ella sightseeing – Nine Arch Bridge & Little Adam’s Peak",
      "Yala National Park wildlife experience",
      "Relax at Mirissa & Whale Watching Tour",
      "Explore Galle Fort (UNESCO) & Turtle Hatchery",
      "Madu River Boat Safari in Balapitiya",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 8,
    title: "One Week Sri Lanka Holiday Tour Package",
    subtitle: "7 Days Tours ",
    duration: "7 Days",
    image: tour1,
    highlights: [
      "Visit Pinnawala Elephant Orphanage",
      "Explore the Temple of the Tooth Relic in Kandy",
      "Scenic drive through Sri Lanka’s tea country",
      "Discover colonial charm of Nuwara Eliya",
      "Enjoy waterfalls: Ramboda, Devon & St. Clair’s",
      "White-water rafting at Kitulgala",
      "Relax on Bentota’s golden beaches",
      "Madu River safari & Turtle Hatchery visit",
      "Explore UNESCO Galle Fort",
      "Colombo city tour with Lotus Tower & Gangaramaya Temple",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 9,
    title: "Sri Lanka 18-Day Heritage & Coastal Odyssey Tour",
    subtitle: "18 Days Tours",
    duration: "18 Days",
    image: tour1,
    highlights: [
      "Relax on golden beaches in Unawatuna & Trincomalee",
      "Galle Fort & colonial heritage exploration",
      "Witness stilt fishermen & southern coast wonders",
      "Full-day Yala National Park jeep safari",
      "Scenic waterfalls & Nine Arch Bridge in Ella",
      "Tea country views from Lipton’s Seat",
      "Temple of the Tooth Relic in Kandy",
      "Dambulla Cave Temple & Sigiriya Rock Fortress",
      "Whale watching & snorkeling at Pigeon Island",
      "Ancient cities of Anuradhapura & Polonnaruwa",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 10,
    title: "13 Days Sri Lanka Surf & Heritage Tour",
    subtitle: "13 Days Tours",
    duration: "13 Days",
    image: tour1,
    highlights: [
      "Climb the UNESCO-listed Sigiriya Rock Fortress",
      "Wildlife Safari at Minneriya National Park",
      "Sunset hike to Pidurangala Rock",
      "Explore Dambulla Golden Cave Temple",
      "Relax at Pasikudah & Kalkudah Beaches",
      "Surf world-class waves at Arugam Bay",
      "Discover Muhudu Maha Viharaya & Pottuvil Lagoon",
      "Scenic hike to Little Adam’s Peak & Ella Rock",
      "Visit Ravana Falls & Nine Arch Bridge in Ella",
      "Surf & chill at Ahangama, Midigama & Kabalana beaches",
      "Experience Sri Lanka’s vibrant culture and rural village life",
    ],
    rating: 4.8,
    reviews: 124,
  },
];
